apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-data-api
  namespace: ghl
  labels:
    app: device-data-api
    tier: web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: device-data-api
      tier: web
  template:
    metadata:
      labels:
        app: device-data-api
        tier: web
    spec:
      containers:
      - name: device-data-api
        image: rodevacr.azurecr.io/device-data-api:v2
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ENVIRONMENT
          value: "PROD"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-password