apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: ghl
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      type: monitor
      app: device-data-api
  namespaceSelector:
    matchNames:
    - ghl
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: ghl
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus